// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -package pgxatomic -source runner.go -destination runner_mocks_test.go txStarter
//

// Package pgxatomic is a generated GoMock package.
package pgxatomic

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MocktxStarter is a mock of txStarter interface.
type MocktxStarter struct {
	ctrl     *gomock.Controller
	recorder *MocktxStarterMockRecorder
	isgomock struct{}
}

// MocktxStarterMockRecorder is the mock recorder for MocktxStarter.
type MocktxStarterMockRecorder struct {
	mock *MocktxStarter
}

// NewMocktxStarter creates a new mock instance.
func NewMocktxStarter(ctrl *gomock.Controller) *MocktxStarter {
	mock := &MocktxStarter{ctrl: ctrl}
	mock.recorder = &MocktxStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktxStarter) EXPECT() *MocktxStarterMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MocktxStarter) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MocktxStarterMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MocktxStarter)(nil).BeginTx), ctx, txOptions)
}
